apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-app2
spec:
   replicas: 2
   selector:
     matchLabels:
         app: my-app2
   template:
     metadata:
         labels:
          app: my-app2
     spec:
         containers:
          - name: nginx2
            image: nginx:latest
            ports:
               - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: svc2
spec:
   type: LoadBalancer
   selector:
      app: my-app2
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80

